version: 3

workflows:
  destroy:
    plan:
      steps:
        - init
        - run: terraform plan -destroy -out=tfplan
    apply:
      steps:
        - run: terraform apply tfplan

projects:
  - dir: .
    workflow: destroy
    autoplan:
      when_modified: ["*.tf", "*.tfvars"]
      enabled: true
    # Allow PRs from all branches
    allowed_overrides: [workflow]
    allow_custom_workflows: true
